### ISSUE TITLE
GameProfile lookup should be threaded

### ISSUE THREAD

**Issue by yyeerai** [blay09/ExCompressum#225]
Version 1.12.2 has a large hysteresis when placed on an automatic sieve

**Comment by blay09** [comment]
Can't reproduce. It's most likely something else in your chunk slowing down the chunk rebuild or general TPS issues. If there is an actual performance issue I need more info.

**Comment by yyeerai** [comment]
![图片](https://s1.ax1x.com/2017/12/23/viAz9.png)
When the auto sieve on the ground, the right click occurs when the situation as shown above

**Comment by blay09** [comment]
Can you check if it still happens when `skipAutoSieveSkins` in the config file is set to true?

**Comment by yyeerai** [comment]
Anyway, there is this problem

**Comment by blay09** [comment]
Then I really can't see how this would be caused by Ex Compressum. Is it maybe related to what's placed down nearby? Have you tried on a new world?

**Comment by yyeerai** [comment]
`20:46:06] [Server thread/WARN]: Couldn't look up profile properties for com.mojang.authlib.GameProfile@34c0a5b8[id=53909932-f794-33c0-9329-948045a4c1ce,name=steve,properties={},legacy=false]
com.mojang.authlib.exceptions.AuthenticationException: No such UUID.
	at com.mojang.authlib.yggdrasil.YggdrasilAuthenticationService.makeRequest(YggdrasilAuthenticationService.java:79) ~[YggdrasilAuthenticationService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillGameProfile(YggdrasilMinecraftSessionService.java:180) [YggdrasilMinecraftSessionService.class:?]
	at com.mojang.authlib.yggdrasil.YggdrasilMinecraftSessionService.fillProfileProperties(YggdrasilMinecraftSessionService.java:173) [YggdrasilMinecraftSessionService.class:?]
	at net.blay09.mods.excompressum.tile.TileAutoSieveBase.grabProfile(TileAutoSieveBase.java:373) [TileAutoSieveBase.class:?]
	at net.blay09.mods.excompressum.tile.TileAutoSieveBase.setCustomSkin(TileAutoSieveBase.java:355) [TileAutoSieveBase.class:?]
	at net.blay09.mods.excompressum.block.BlockAutoSieveBase.func_180633_a(BlockAutoSieveBase.java:202) [BlockAutoSieveBase.class:?]
	at net.blay09.mods.excompressum.block.BlockAutoSieve.func_180633_a(BlockAutoSieve.java:44) [BlockAutoSieve.class:?]
	at net.minecraft.item.ItemBlock.placeBlockAt(ItemBlock.java:186) [ahb.class:?]
	at net.minecraft.item.ItemBlock.func_180614_a(ItemBlock.java:54) [ahb.class:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:851) [ForgeHooks.class:?]
	at net.minecraft.item.ItemStack.func_179546_a(ItemStack.java:186) [aip.class:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_187251_a(PlayerInteractionManager.java:478) [or.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_184337_a(NetHandlerPlayServer.java:739) [pa.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:55) [ma.class:?]
	at net.minecraft.network.play.client.CPacketPlayerTryUseItemOnBlock.func_148833_a(SourceFile:11) [ma.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_131]
	at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_131]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:721) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:239) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
[20:46:06] [Server thread/WARN]: Can't keep up! Did the system time change, or is the server overloaded? Running 2487ms behind, skipping 49 tick(s)`

**Comment by blay09** [comment]
The log helped. Please try [this version](http://jenkins.blay09.net/job/Ex%20Compressum%201.12/12/artifact/build/libs/ExCompressum_1.12.2-3.0.12.jar) which should hopefully fix the issue.
