### ISSUE TITLE
Crash when mob killed

### ISSUE THREAD

**Issue by Josephur** [blay09/ExCompressum#34]
Every 20th or so mob killed on my server crashes and Ex Compressum seems to be at fault.

Error:
[21:43:22] [Server thread/ERROR] [FML/]: Exception caught during firing event net.minecraftforge.event.entity.living.LivingDeathEvent@2f32b8ae:
java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_70016_h(DDD)V
	at net.blay09.mods.excompressum.handler.CompressedEnemyHandler.onEntityDeath(CompressedEnemyHandler.java:49) ~[CompressedEnemyHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_237_CompressedEnemyHandler_onEntityDeath_LivingDeathEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.common.ForgeHooks.onLivingDeath(ForgeHooks.java:303) [ForgeHooks.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:891) [sv.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:855) [sv.class:?]
	at net.minecraft.entity.monster.EntityMob.func_70097_a(SourceFile:54) [yg.class:?]
	at net.minecraft.entity.monster.EntityEnderman.func_70097_a(EntityEnderman.java:431) [ya.class:?]
	at net.minecraft.entity.player.EntityPlayer.func_71059_n(EntityPlayer.java:1232) [yz.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147340_a(NetHandlerPlayServer.java:821) [nh.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:55) [ja.class:?]
	at net.minecraft.network.play.client.C02PacketUseEntity.func_148833_a(SourceFile:10) [ja.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]

All mods in use:
accidentallycircumstantialevents-1.12.0.jar
ae2stuff-0.5.0.56-mc1.7.10.jar
AgriCraft-1.7.10-1.5.0.jar
AppleCore-mc1.7.10-1.3.0.jar
appliedenergistics2-rv3-beta-5.jar
Aroma1997Core-1.7.10-1.0.2.16.jar
AromaBackup-1.7.10-0.1.0.0.jar
Automagy-1.7.10-0.28.2.jar
autopackager-1.5.9.jar
Bagginses-2.1.1.jar
bdlib-1.9.4.109-mc1.7.10.jar
BiblioCraft[v1.11.4][MC1.7.10].jar
BiblioWoods[Forestry][v1.7].jar
BiblioWoods[Natura][v1.5].jar
BigReactors-0.4.3A.jar
BiomeTweaker-1.7.10-2.0.182.jar
BloodMagic-1.7.10-1.3.3-17.jar
Botania r1.8-249.jar
CodeChickenCore-1.7.10-1.0.7.47-universal.jar
CoFHCore-[1.7.10]3.1.2-325.jar
CoFHLib-[1.7.10]1.1.1-181.jar
compactstorage-1.7.10-release-2.1.0-lts.21-universal.jar
cookingbook-mc1.7.10-1.0.134.jar
CustomMainMenu-MC1.7.10-1.7.1.jar
CustomNPCs_1.7.10d.jar
Ding-MC1.7.10v2.jar
Enchiridion 2-1.7.10-2.0.2a.jar
EnderTech-1.7.10-0.3.2.405.jar
Ex-Astris-MC1.7.10-1.16-36.jar
Ex-Nihilo-1.38-49.jar
excompressum-mc1.7.10-1.1.54.jar
ExtraTiC-1.7.10-1.4.5.jar
extrautilities-1.2.12.jar
FinndusFillies-1.7.10-universal-2.1.0.12.jar
FlatSigns-1.7.10-universal-2.1.0.19.jar
Forbidden Magic-1.7.10-0.573.jar
forestry_1.7.10-4.2.9.57.jar
ForgeMultipart-1.7.10-1.2.0.345-universal.jar
gendustry-1.6.3.132-mc1.7.10.jar
gud_thaumicnei-1.3.0.jar
Guide-API-1.7.10-1.0.1-23.jar
HardCoreMapReset-2.2.0.jar
Headcrumbs-1.7.4.jar
HQM-The Journey-4.4.4.jar
HungerOverhaul-1.7.10-1.0.0.jar
IguanaTinkerTweaks-1.7.10-2.1.5.jar
INpureCore-[1.7.10]1.0.0B9-62.jar
InventoryTweaks-1.59-dev-152.jar
Jabba-1.2.1a_1.7.10.jar
JadedsShinies-1.7.10-1.2.jar
jctweaks-1.7.10-1.26.jar
journeymap-1.7.10-5.1.4-unlimited.jar
LaunchGui-1.7.10-2.0-18-client.jar
magicbees-1.7.10-2.4.3.jar
Mantle-1.7.10-0.3.2b.jar
MineFactoryReloaded-[1.7.10]2.8.2B1-177.jar
MobiusCore-1.2.5_1.7.10.jar
natura-1.7.10-2.2.1a2.jar
neiaddons-1.12.15.41-mc1.7.10.jar
NEIIntegration-MC1.7.10-1.1.2.jar
NetherOres-[1.7.10]2.3.1-22.jar
NodalMechanics-1.7-1.0-7.jar
NotEnoughItems-1.7.10-1.0.5.118-universal.jar
ObsidiPlates-1.7.10-universal-3.0.0.18.jar
PackGuard-1.3.2.jar
Pam's HarvestCraft 1.7.10Lb.jar
ProgressiveAutomation-1.7.10-1.6.34.jar
Rainmaker 1.7-BloodMagic.jar
RecallStones-1.7.10-0.5.2.jar
RedstoneArsenal-[1.7.10]1.1.2-92.jar
RefinedRelocation-mc1.7.10-1.1.25.jar
ResourceLoader-1.2.jar
rfwindmill-1.7.10-0.7c.jar
RouterReborn-1.7.10-1.2.0.41-universal.jar
Sanguimancy-1.7.10-1.1.9-33.jar
SimpleLabels-1.7.10-1.0-7.jar
SimplyJetpacks-MC1.7.10-1.5.3.jar
SolarFlux-1.7.10-0.8b.jar
SpecialAI-1.7.10-1.1.2.jar
SquidAPI-1.1.15.jar
StevesWorkshop-0.5.1.jar
StorageDrawers-1.7.10-1.9.4.jar
StorageDrawers-Natura-1.7.10-1.1.1.jar
supercraftingframe-1.7.10.3.jar
tcnodetracker-1.7.10-1.1.2.jar
TConstruct-1.7.10-1.8.8.build991.jar
Thaumcraft-1.7.10-4.2.3.5.jar
thaumcraftneiplugin-1.7.10-1.7a.jar
thaumicenergistics-1.0.0.1.jar
thaumichorizons-1.7.10-1.1.9.jar
thermalcasting-0.0.3.jar
ThermalDynamics-[1.7.10]1.1.0-161.jar
ThermalExpansion-[1.7.10]4.1.2-240.jar
ThermalFoundation-[1.7.10]1.2.3-112.jar
TiCTooltips-mc1.7.10-1.2.5.jar
Town-Builder-1.0.0-Build8.jar
TravellersGear-1.7.10-1.16.6.jar
Waila-1.5.10_1.7.10.jar
WailaHarvestability-mc1.7.10-1.1.6.jar
WitchingGadgets-1.7.10-1.1.10.jar

**Comment by Josephur** [comment]
Your update has resolved the issue, closing.
