### ISSUE TITLE
[1.18.2] Incompatibility with Jade (Waila fork)

### ISSUE THREAD

**Issue by Chaos02** [blay09/ExCompressum#356]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Mod Version

5.0.2

### Describe the Issue

This message in my latest.log:

```
[Worker-Main-6/ERROR] [Waila/]: Error loading plugin at net.blay09.mods.excompressum.compat.waila.ExCompressumWailaPlugin
java.lang.NoClassDefFoundError: mcp/mobius/waila/api/IBlockComponentProvider
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at mcp.mobius.waila.Waila.loadComplete(Waila.java:111) ~[Jade-1.18.2-forge-5.2.3.jar%23248!/:5.2.3]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:106) ~[javafmllanguage-1.18.2-40.1.73.jar%23411!/:?]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:107) ~[fmlcore-1.18.2-40.1.73.jar%23410!/:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: java.lang.ClassNotFoundException: mcp.mobius.waila.api.IBlockComponentProvider
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:138) ~[securejarhandler-1.0.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 16 more
```

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Rubidium, along many more but unrelated

**Comment by CapivaraTupiniquim** [comment]
I think I figured out my problem, the game crashes when I add a block from the mod to the world

**Comment by BlayTheNinth** [comment]
Ex Compressum will properly support Jade/WTHIT in 1.19. However, there shouldn't be any crashes related to this even in 1.18.

**Comment by Chaos02** [comment]
> Ex Compressum will properly support Jade/WTHIT in 1.19. However, there shouldn't be any crashes related to this even in 1.18.

It doesn't crash the game, you're right there.
However, please consider backporting compatibility to 1.18 as it is the main modding version at the moment.

**Comment by BlayTheNinth** [comment]
Closing since there's no good way of fixing this in 1.18. See https://github.com/TwelveIterationMods/Waystones/issues/564#issuecomment-1302252840 and https://github.com/TwelveIterationMods/Waystones/issues/603
