### ISSUE TITLE
Could not load remote skins for auto sieve

### ISSUE THREAD

**Issue by Ironnoob73** [blay09/ExCompressum#367]
### Minecraft Version

1.12.x

### Mod Loader

Forge

### Mod Loader Version

14.23.5.2860

### Mod Version

3.0.32

### Describe the Issue

Auto sieves cannot read skin automatically. Using nametags still works.
```
Could not load remote skins for auto sieve: 
com.google.gson.JsonSyntaxException: Expected a com.google.gson.JsonObject but was com.google.gson.JsonPrimitive
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:913) ~[TypeAdapters$35$1.class:?]
	at com.google.gson.Gson.fromJson(Gson.java:887) ~[Gson.class:?]
	at net.blay09.mods.excompressum.registry.AutoSieveSkinRegistry.lambda$load$0(AutoSieveSkinRegistry.java:31) ~[AutoSieveSkinRegistry.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_251]
```

**Comment by WinterSoldier290** [comment]
I have the same problem on 1.18.2, Forge 40.1.48
[Thread-1/ERROR] [excompressum/]: Could not load remote skins for auto sieve: >

**Comment by BlayTheNinth** [comment]
Is this causing a crash or just logging an error? The error log is expected, as older versions are trying to sieve skins from an endpoint that is no longer active.

**Comment by Ironnoob73** [comment]
No crashes.
